### ISSUE TITLE
Cannot load FK pose on character which used cloth overlay mod in studio 

### ISSUE THREAD

**Issue by CodyLTH** [ManlyMarco/Koikatu-Overlay-Mods#2]
No problem on Character without cloth overlay.
Not sure if there are same problem on skin overlay.

**Comment by CodyLTH** [comment]
Update: Pose loaded well on KCOX character when the current clothing is not KCOX used, problem only happen when the current clothing used KCOX.

**Comment by ManlyMarco** [comment]
It works on me, can you send your studio output_log.txt after you get this issue to happen?

**Comment by CodyLTH** [comment]
Here is it,
[output_log.txt](https://github.com/ManlyMarco/Koikatu-Overlay-Mods/files/2988093/output_log.txt)

I mentioned that "problem only happen when the current clothing used KCOX" but it is wrong,
the problem happened on KCOX used character when it is loaded (in school uniform state, doesn't matter to it used KCOX or not), but the problem solves once the coordinate changed, the problem don't happened on that character again even the current clothing is KCOX used (still get the problem if I load a new character with the same KCOX card).

**Comment by ManlyMarco** [comment]
Fixed in the upcoming version, thank you for the report!
