### ISSUE TITLE
Problems with PNG Transparency

### ISSUE THREAD

**Issue by SiTWulf** [ManlyMarco/Koikatu-Overlay-Mods#3]
The last version 4.1.1 include a bug with PNG transparency, for example the Freckles overlay become BLACK without any transparency.
Tried with 3.2 and works perfect.

**Comment by ManlyMarco** [comment]
Can you try this build? It should be fixed now.
[BepInEx.zip](https://github.com/ManlyMarco/Koikatu-Overlay-Mods/files/2984379/BepInEx.zip)

**Comment by SiTWulf** [comment]
Yeah!!! This version works like a charm... not problems with PNGs transparency.

**Comment by ManlyMarco** [comment]
Good to hear!
