### ISSUE TITLE
Cloth overlay don't work well in studio

### ISSUE THREAD

**Issue by CodyLTH** [ManlyMarco/Koikatu-Overlay-Mods#4]
Cloth overlay is not loaded to coordinate when loading a new character. Again, problem solved when coordinate changed. If I overwrite a KCOX chara with a KCOX chara, cloths were still using the old overlay texture until coordinate changed. If KCOX chara was saved in a scene, the problem also happen when scene is loaded.

Here is the output log of studio
[output_log.txt](https://github.com/ManlyMarco/Koikatu-Overlay-Mods/files/3040805/output_log.txt)
Thank you very much.

**Comment by ManlyMarco** [comment]
Sorry for the slow reply. Does this still happen 4.1.3.1? You can get it here https://www.patreon.com/posts/25512242

**Comment by CodyLTH** [comment]
4.1.3.1 works. Sorry about that. I didn't know there are already a bugfix of 4.1.3 . I checked the release date but I didn't expect that was released on the same day. Thank you for the quick response.
